name: Deploy Flask App

on:
  push:
    branches:
      - easyocr

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.NYCU_HOST }}
        username: ${{ secrets.NYCU_USER }}  
        key: ${{ secrets.NYCU_SSH_KEY }}  
        port: 22
        script: |
          ssh -vvv -o StrictHostKeyChecking=no ${{ secrets.NYCU_USER }}@${{ secrets.NYCU_HOST }}
          cd /home/bclab-ai/Projects/science_video_OCR/
          git pull origin easyocr
          source /home/bclab-ai/Projects/science_video_OCR/venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl start gunicorn_science_video_OCR