name: Deploy Flask App

on:
  push:
    branches:
      - easyocr

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.NYCU_HOST }}
        username: ${{ secrets.NYCU_USER }}  
        key: ${{ secrets.NYCU_SSH_KEY }}  
        port: 22
        script: |
          sudo systemctl stop gunicorn
          cd /home/laitup/science_video_OCR/
          git pull
          source /home/laitup/science_video_OCR/venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl start gunicorn